import type { Car } from './types';
import { ListingType } from './types';

export const CARS: Car[] = [
  // Cars for Sale
  {
    id: 1,
    name: 'تويوتا كامري',
    brand: 'تويوتا',
    year: 2023,
    price: 2800000,
    type: ListingType.SALE,
    imageUrl: 'https://www.toyota.com/imgix/responsive/images/gallery/2023/camry/CAM_MY23_0002_V001.png?w=1600&q=90&fm=webp&fit=max&cs=strip&bg=fff',
    mileage: '15,000 كم',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  {
    id: 2,
    name: 'فورد موستانج',
    brand: 'فورد',
    year: 2024,
    price: 3500000,
    type: ListingType.SALE,
    imageUrl: 'https://images.hdqwalls.com/download/red-ford-mustang-gt-2024-5k-v8-1920x1080.jpg',
    mileage: 'جديدة',
    fuelType: 'بنزين',
    transmission: 'يدوي',
  },
  {
    id: 3,
    name: 'نيسان باترول',
    brand: 'نيسان',
    year: 2023,
    price: 3200000,
    type: ListingType.SALE,
    imageUrl: 'https://www.nissan-cdn.net/content/dam/Nissan/me/vehicles/patrol/Y62-2023/Y62_PATROL-Platinum-V8_Front-Side.jpg.ximg.l_full_m.smart.jpg',
    mileage: '5,000 كم',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  {
    id: 4,
    name: 'مرسيدس بنز C-Class',
    brand: 'مرسيدس',
    year: 2022,
    price: 2500000,
    type: ListingType.SALE,
    imageUrl: 'https://www.mercedes-benz-mena.com/en/passengercars/models/saloon/c-class/w206/_jcr_content/root/responsivegrid/simple_stage.component.dam.html/content-pool-de-passenger-cars-mercedes-benz-c-class-w206-exterior-gallery-3840x3840-02-2021.jpeg',
    mileage: '25,000 كم',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  {
    id: 5,
    name: 'لادا جرانتا',
    brand: 'لادا',
    year: 2023,
    price: 550000,
    type: ListingType.SALE,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Lada_Granta_Liftback_2018.jpg/1280px-Lada_Granta_Liftback_2018.jpg',
    mileage: 'جديدة',
    fuelType: 'بنزين',
    transmission: 'يدوي',
  },
  {
    id: 6,
    name: 'هيونداي كريتا',
    brand: 'هيونداي',
    year: 2024,
    price: 1100000,
    type: ListingType.SALE,
    imageUrl: 'https://s7d1.scene7.com/is/image/hyundai/2024-creta-gallery-02-1:16x9?wid=1200&hei=675&qlt=85,0&fmt=webp',
    mileage: 'جديدة',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  {
    id: 7,
    name: 'نيسان صني',
    brand: 'نيسان',
    year: 2023,
    price: 850000,
    type: ListingType.SALE,
    imageUrl: 'https://www.drivespark.com/images/2017/01/17-1484640191-2017-nissan-sunny-facelift-exterior-images-2.jpg',
    mileage: '10,000 كم',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  {
    id: 8,
    name: 'شيري تيجو 7 برو',
    brand: 'شيري',
    year: 2024,
    price: 1250000,
    type: ListingType.SALE,
    imageUrl: 'https://www.alahliauto.com/wp-content/uploads/2021/07/Tiggo-7-Pro-2022-Exterior-3.jpg',
    mileage: 'جديدة',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  
  // Cars for Rent
  {
    id: 9,
    name: 'هيونداي إلنترا',
    brand: 'هيونداي',
    year: 2022,
    price: 950,
    type: ListingType.RENT,
    imageUrl: 'https://s7d1.scene7.com/is/image/hyundai/2022-elantra-gallery-limited-03-1:16x9?wid=1200&hei=675&qlt=85,0&fmt=webp',
    mileage: '30,000 كم',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  {
    id: 10,
    name: 'كيا سبورتاج',
    brand: 'كيا',
    year: 2024,
    price: 1200,
    type: ListingType.RENT,
    imageUrl: 'https://www.kia.com/content/dam/kw/en/vehicles/sportage-2024/gallery/kia-sportage-my24-gallery-01-l.jpg',
    mileage: 'جديدة',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  {
    id: 11,
    name: 'شيفروليه تاهو',
    brand: 'شيفروليه',
    year: 2023,
    price: 2500,
    type: ListingType.RENT,
    imageUrl: 'https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2023/crossovers-suvs/tahoe/gallery/2023-tahoe-z71-gph-01.jpg?imwidth=960',
    mileage: '12,000 كم',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  {
    id: 12,
    name: 'فولكس فاجن طوارق',
    brand: 'فولكس فاجن',
    year: 2023,
    price: 1800,
    type: ListingType.RENT,
    imageUrl: 'https://www.topgear.com/sites/default/files/2023/04/1%20VW%20Touareg%20R%20facelift.jpg',
    mileage: '5,000 كم',
    fuelType: 'بنزين',
    transmission: 'أوتوماتيك',
  },
  {
    id: 13,
    name: 'مرسيدس بنز S-Class',
    brand: 'مرسيدس',
    year: 2023,
    price: 3500,
    type: ListingType.RENT,
    imageUrl: 'https://www.mercedes-benz.com/en/vehicles/passenger-cars/s-class/s-class-saloon-2023/_jcr_content/root/fullscreen_teaser/fullscreen_teaser_item.component.dam.v1.20230719131641.jpg/mercedes-benz-s-class-z223-exterior-3840x3840.jpg',
    mileage: '8,000 كم',
    fuelType: 'ديزل',
    transmission: 'أوتوماتيك',
  }
];